# Generated by Django 3.0.3 on 2021-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20210830_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('delay_time', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100)),
            ],
        ),
    ]
