# Generated by Django 3.0.3 on 2021-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='projects/photo/'),
        ),
    ]
