# Generated by Django 3.0.3 on 2021-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_auto_20210830_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filter_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
