# Generated by Django 3.0.3 on 2021-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0006_project_filter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='projects/photo/')),
                ('profession', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
