# Generated by Django 3.0.3 on 2021-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='projects/photo/')),
                ('profession', models.CharField(blank=True, max_length=20)),
                ('blog_name', models.CharField(blank=True, max_length=50)),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
